// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "OI.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/ClimbALevel.h"
#include "Commands/JoystickDrive.h"
#include "Commands/ThrowerOff.h"
#include "Commands/ThrowerOn.h"
#include "Commands/TilterSpeed.h"
#include "Commands/TimedDiscKicker.h"
#include "Commands/TimedDriveStraight.h"
#include "Commands/TimedTilterSpeed.h"
#include "Commands/ToggleRobotClimb.h"
#include "Commands/ToggleRobotTilt.h"
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "Commands/KickerSpeed.h"
OI::OI() {
	// Process operator interface input here.
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	joystick2 = new Joystick(2);
	
	joystick1 = new Joystick(1);
	
     
        // SmartDashboard Buttons
	SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	SmartDashboard::PutData("TimedTilterSpeed", new TimedTilterSpeed(0.20, 0.1));
	SmartDashboard::PutData("ToggleRobotTilt", new ToggleRobotTilt());
	SmartDashboard::PutData("ToggleRobotClimb", new ToggleRobotClimb());
	SmartDashboard::PutData("Tilter15Down", new TilterSpeed(0.15));
	SmartDashboard::PutData("Tilter15Up", new TilterSpeed(-0.15));
	SmartDashboard::PutData("Tilter20Down", new TilterSpeed(0.20));
	SmartDashboard::PutData("Tilter20Up", new TilterSpeed(-0.20));
	SmartDashboard::PutData("Tilter25Down", new TilterSpeed(0.25));
	SmartDashboard::PutData("Tilter25Up", new TilterSpeed(-0.25));
	SmartDashboard::PutData("Tilter30Down", new TilterSpeed(0.30));
	SmartDashboard::PutData("Tilter30Up", new TilterSpeed(-0.30));
	SmartDashboard::PutData("JoystickDrive", new JoystickDrive());
//	SmartDashboard::PutData("TimedDiscKicker50", new TimedDiscKicker(0.5, 1.32));
//	SmartDashboard::PutData("TimedDiscKicker60", new TimedDiscKicker(0.6, 1.163));
//	SmartDashboard::PutData("TimedDiscKicker70", new TimedDiscKicker(0.7, 0.962));
//	SmartDashboard::PutData("TimedDiscKicker80", new TimedDiscKicker(0.8, 0.833));
//	SmartDashboard::PutData("TimedDiscKicker90", new TimedDiscKicker(0.9, 0.73));
//	SmartDashboard::PutData("TimedDiscKicker100", new TimedDiscKicker(1.0, 0.649));
	SmartDashboard::PutData("TimedDriveStraight12", new TimedDriveStraight(0.5, 5.0));
	//SmartDashboard::PutData("ClimbALevel5", new ClimbALevel());
	SmartDashboard::PutData("ThrowerOn3", new ThrowerOn());
	SmartDashboard::PutData("ThrowerOff3", new ThrowerOff());
	SmartDashboard::PutData("KickerSpeedOn4", new KickerSpeed(0.6));
	SmartDashboard::PutData("KickerSpeedOff4", new KickerSpeed(0.0));
	SmartDashboard::PutData("KickerSpeedRev4", new KickerSpeed(-0.6));
}
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
Joystick* OI::getJoystick2() {
	return joystick2;
}
Joystick* OI::getJoystick1() {
	return joystick1;
}
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
