// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#ifndef OI_H
#define OI_H
#include "WPILib.h"
class OI
{
private:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	Joystick* joystick2;
	Joystick* joystick1;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	JoystickButton* m_dualActionB1;
	JoystickButton* m_dualActionB2;
	JoystickButton* m_dualActionB3;
	JoystickButton* m_dualActionB4;
	JoystickButton* m_dualActionB5;
	JoystickButton* m_dualActionB6;
	JoystickButton* m_dualActionB7;
	JoystickButton* m_dualActionB8;
	JoystickButton* m_dualActionB10;
	
	JoystickButton* m_ATK3B6;
	JoystickButton* m_ATK3B7;
public:
	OI();
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES
	Joystick* getJoystick1();
	Joystick* getJoystick2();
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES
};
#endif
