// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
SpeedController* RobotMap::chassisLeftMotor = NULL;
SpeedController* RobotMap::chassisRightMotor = NULL;
RobotDrive* RobotMap::chassisRobotDrive21 = NULL;
Gyro* RobotMap::chassisAlignmentGyro = NULL;
SpeedController* RobotMap::discThrowerMotor = NULL;
SpeedController* RobotMap::climberMotor = NULL;
DoubleSolenoid* RobotMap::climberAirAssist = NULL;
DigitalInput* RobotMap::climberForwardLimit = NULL;
DigitalInput* RobotMap::climberReverseLimit = NULL;
SpeedController* RobotMap::tiltTableMotor = NULL;
DigitalInput* RobotMap::tiltTableFullTiltLimit = NULL;
DigitalInput* RobotMap::tiltTableNoTiltLimit = NULL;
DoubleSolenoid* RobotMap::pneumaticsRobotTilt = NULL;
DoubleSolenoid* RobotMap::pneumaticsRobotClimb = NULL;
Compressor* RobotMap::pneumaticsCompressor = NULL;
SpeedController* RobotMap::discKickermotor = NULL;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
ADXL345_I2C* RobotMap::tiltTableTiltCalculator = NULL;
void RobotMap::init() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	LiveWindow* lw = LiveWindow::GetInstance();
	chassisLeftMotor = new Talon(1, 1);
	lw->AddActuator("Chassis", "LeftMotor", (Talon*) chassisLeftMotor);
	
	chassisRightMotor = new Talon(1, 2);
	lw->AddActuator("Chassis", "RightMotor", (Talon*) chassisRightMotor);
	
	chassisRobotDrive21 = new RobotDrive(chassisLeftMotor, chassisRightMotor);
	
	chassisRobotDrive21->SetSafetyEnabled(false);
        chassisRobotDrive21->SetExpiration(0.5);
        chassisRobotDrive21->SetSensitivity(0.5);
        chassisRobotDrive21->SetMaxOutput(1.0);
        chassisRobotDrive21->SetInvertedMotor(RobotDrive::kRearLeftMotor, true);
        chassisRobotDrive21->SetInvertedMotor(RobotDrive::kRearRightMotor, true);        
	chassisAlignmentGyro = new Gyro(1, 1);
	lw->AddSensor("Chassis", "AlignmentGyro", chassisAlignmentGyro);
	chassisAlignmentGyro->SetSensitivity(0.007);
	discThrowerMotor = new Talon(1, 3);
	lw->AddActuator("DiscThrower", "Motor", (Talon*) discThrowerMotor);
	
	climberMotor = new Talon(1, 5);
	lw->AddActuator("Climber", "Motor", (Talon*) climberMotor);
	
	climberAirAssist = new DoubleSolenoid(1, 1, 2);      
	
	
	climberForwardLimit = new DigitalInput(1, 1);
	lw->AddSensor("Climber", "ForwardLimit", climberForwardLimit);
	
	climberReverseLimit = new DigitalInput(1, 2);
	lw->AddSensor("Climber", "ReverseLimit", climberReverseLimit);
	
	tiltTableMotor = new Jaguar(1, 6);
	lw->AddActuator("TiltTable", "Motor", (Jaguar*) tiltTableMotor);
	
	tiltTableFullTiltLimit = new DigitalInput(1, 3);
	lw->AddSensor("TiltTable", "FullTiltLimit", tiltTableFullTiltLimit);
	
	tiltTableNoTiltLimit = new DigitalInput(1, 4);
	lw->AddSensor("TiltTable", "NoTiltLimit", tiltTableNoTiltLimit);
	
	pneumaticsRobotTilt = new DoubleSolenoid(1, 3, 4);      
	
	
	pneumaticsRobotClimb = new DoubleSolenoid(1, 5, 6);      
	
	
	pneumaticsCompressor = new Compressor(1, 5, 1, 1);
	
	
	discKickermotor = new Talon(1, 4);
	lw->AddActuator("DiscKicker", "motor", (Talon*) discKickermotor);
	
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	tiltTableTiltCalculator = new ADXL345_I2C(1);
	//lw->AddSensor("TiltTable", "TiltCalculator", tiltTableTiltCalculator);
	chassisAlignmentGyro->SetSensitivity(0.007);
}
