// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.

#include "KickerSpeed.h"

KickerSpeed::KickerSpeed(double speed)
: m_speed(speed)
{
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::discKicker);
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
void KickerSpeed::Initialize()
{
	Robot::discKicker->Initialize(m_speed);
}
// Called repeatedly when this Command is scheduled to run
void KickerSpeed::Execute()
{
	Robot::discKicker->SetSpeed();
}
// Make this return true when this Command no longer needs to run execute()
bool KickerSpeed::IsFinished()
{
	return false;
}
// Called once after isFinished returns true
void KickerSpeed::End()
{
	Robot::discKicker->Initialize(0.0);
	Robot::discKicker->SetSpeed();
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void KickerSpeed::Interrupted()
{
	End();
}
