// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "TimedDriveStraight.h"
TimedDriveStraight::TimedDriveStraight(double driveSpeed, double timeout) 
: m_driveSpeed(driveSpeed),
  m_timeout(timeout)
{
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::chassis);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// Called just before this Command runs the first time
void TimedDriveStraight::Initialize()
{
	if (m_timeout > 0)
	{
		SetTimeout(m_timeout);
	}
}
// Called repeatedly when this Command is scheduled to run
void TimedDriveStraight::Execute()
{
	Robot::chassis->TankDrive(-m_driveSpeed, -m_driveSpeed);
}
// Make this return true when this Command no longer needs to run execute()
bool TimedDriveStraight::IsFinished()
{
	if (m_timeout > 0.0)
	{ 
		return IsTimedOut();
	}
	else
	{
		return false;
	}
}
// Called once after isFinished returns true
void TimedDriveStraight::End()
{
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void TimedDriveStraight::Interrupted()
{
	End();
}
