// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


#ifndef TIMEDDRIVESTRAIGHT_H
#define TIMEDDRIVESTRAIGHT_H

#include "Commands/Subsystem.h"
#include "../Robot.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class TimedDriveStraight : public Command
{
public:
	// Drives forward at the given speed for the given time (in seconds).
	// If the given time is less than zero, will drive forever.
	TimedDriveStraight(double driveSpeed, double timeout);
	virtual void Initialize();
	virtual void Execute();
	virtual bool IsFinished();
	virtual void End();
	virtual void Interrupted();
	
private:
	double m_driveSpeed;
	double m_timeout;
};

#endif
