// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "Chassis.h"
#include "../Robotmap.h"
#include "../Commands/DriveWithJoystick.h"
Chassis::Chassis() :
	Subsystem("Chassis")
{
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	leftMotor = RobotMap::chassisLeftMotor;
	rightMotor = RobotMap::chassisRightMotor;
	robotDrive21 = RobotMap::chassisRobotDrive21;
	alignmentGyro = RobotMap::chassisAlignmentGyro;
	magRotaryEncoder = RobotMap::chassisMagRotaryEncoder;
	irSensor = RobotMap::chassisIrSensor;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}
void Chassis::InitDefaultCommand()
{
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	SetDefaultCommand(new DriveWithJoystick());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}
void Chassis::TankDrive(double left, double right)
{
	robotDrive21->TankDrive(left, right);
}
void Chassis::JoystickDrive(Joystick *stick)
{
	robotDrive21->ArcadeDrive(stick);
	SmartDashboard::PutNumber("RotaryEncoderV", magRotaryEncoder->GetVoltage());
	SmartDashboard::PutBoolean("IrSensor", irSensor->Get());
}
void Chassis::TurnLeft()
{
	robotDrive21->ArcadeDrive(0.0, -0.3);
}
void Chassis::TurnRight()
{
	robotDrive21->ArcadeDrive(0.0, 0.3);
}
