// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#ifndef CLIMBER_H
#define CLIMBER_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
/**
 *
 *
 * @author ExampleAuthor
 */
class Climber: public Subsystem {
private:
	// It's desirable that everything possible under private except
	// for methods that implement subsystem capabilities
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	SpeedController* motor;
	DoubleSolenoid* airAssist;
	DigitalInput* forwardLimit;
	DigitalInput* reverseLimit;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	Climber();
	void InitDefaultCommand();
	// This initializes the climbing rate and starts the climb.
	// Speed can be from 0 to 100 (percent).
	void InitializeAndStartClimb(unsigned int speed);
	// This is called in a periodic fashion from the command
	void SetSpeed();
	// Returns true when the switch closes.
	bool IsAtLimitSwitch();
	// Stops the motor
	void Stop();
	
private:
	bool m_movingForward;
	double m_motorSpeed;
};
#endif
