// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "DiscThrower.h"
#include "../Robotmap.h"
DiscThrower::DiscThrower() :
	Subsystem("DiscThrower"),
	m_motorSpeed(0.0)
{
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	motor = RobotMap::discThrowerMotor;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}
void DiscThrower::InitDefaultCommand()
{
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}
void DiscThrower::InitializeMotorSpeed(double speed)
{
	m_motorSpeed = speed;
}
void DiscThrower::ExecuteMotorSpeed()
{
	motor->Set(m_motorSpeed);
}
void DiscThrower::EndMotorSpeed()
{
	motor->Set(0.0);
}
