// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#ifndef TILTTABLE_H
#define TILTTABLE_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
/**
 *
 *
 * @author ExampleAuthor
 */
class TiltTable : public Subsystem
{
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	SpeedController* motor;
	DigitalInput* downTiltLimit;
	DigitalInput* autonomousSwitch;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	ADXL345_I2C* tiltCalculator;
	TiltTable();
	void InitDefaultCommand();
	// Speed can be from -1.0 to 1.0.
	void InitializeMotorSpeed(double speed);
	// This is called in a periodic fashion from the command
	void ExecuteMotorSpeed();
	// Stops the motor
	void EndMotorSpeed();
	// Queries the Auto Switch.  If closes, returns true;
	bool IsAutonomousSwitch();
private:
	// It's desirable that everything possible under private except
	// for methods that implement subsystem capabilities
	double m_motorSpeed;
};
#endif
